### ISSUE TITLE
[Feature] Next Major Update

### ISSUE THREAD

**Issue by SteveKunG** [SteveKunG/FishOfThieves#1]
- [x] Fish Plaques
- [ ] Bone Fish
* A hostile fish mob
* Spawn Egg
* Bone Fish in the bucket.
- [ ] AI Update
* More playful Splashtails, etc.
* Trophy Fish will act as leader.
- [x] Seaposts
* A small structure generated at the ocean. Which has a Villager to buy the fish just like in the Sea of Thieves.
* Config to enable/disable.

**Comment by viiizee** [comment]
These are sweet ideas

**Comment by Telezhka-the-First** [comment]
Make it so that basically everything on this list has a setting to toggle some feature on/off, especially structure generation

**Comment by Redd56** [comment]
i 2nd a list of blocks that gets called, with extra mods i could easily add things to a list of sand dirt and mud types

**Comment by ryleu** [comment]
i think it'd be so cool if you got a bonus to luck when casting with any type of worm in your offhand (it'd obviously use one of the worms)

**Comment by SteveKunG** [comment]
Closing this, now I'm moving this to GitHub Project.
