### ISSUE TITLE
[1.19] Too many Fish in Treasure Chest

### ISSUE THREAD

**Issue by pewblaze** [SteveKunG/FishOfThieves#14]
Hi
I think there are a few too many fishes in the Buried Treasure Chest. Is this intended? 

![grafik](https://user-images.githubusercontent.com/96242065/178292354-a7a7fa25-d6d1-46b7-a581-001e227ec0a8.png)

**Comment by SteveKunG** [comment]
Ah, It will be rebalanced on the next update.

**Comment by SteveKunG** [comment]
This fix will be applied on 1.18.2 as well.
![image](https://user-images.githubusercontent.com/6128413/180615626-ad275fac-7842-4fab-8291-f3905a59856d.png)
