### ISSUE TITLE
Incompatible with Fabric API 0.60.x

### ISSUE THREAD

**Issue by xR4YM0ND** [SteveKunG/FishOfThieves#19]
[latest.log](https://gist.github.com/SpigotDE/ec67365edae0607b5ec312607b51e58a)

**Comment by SteveKunG** [comment]
Stay on Fabric API 0.59.x, do not update FAPI, will fix this later.

**Comment by xR4YM0ND** [comment]
Kk

**Comment by SteveKunG** [comment]
Uploaded rc-1 on CurseForge and Modrinth, highly recommended to backup your map!
