### ISSUE TITLE
Crashing: Failed to Create Model

### ISSUE THREAD

**Issue by viiizee** [SteveKunG/FishOfThieves#23]
Game keeps crashing.
[crash-2022-09-05_21.24.19-client.txt](https://github.com/SteveKunG/FishOfThieves/files/9493267/crash-2022-09-05_21.24.19-client.txt)

Forge Version: 1.18.2 - 40.1.73
Fish of Thieves: Latest Forge
Cloth Config: Updated to latest and crash persists.

**Comment by sijalids** [comment]
how did you fix it?
