### ISSUE TITLE
Crash: Rending Overlay

### ISSUE THREAD

**Issue by viiizee** [SteveKunG/FishOfThieves#24]
Forge 1.18.2 - 40.1.73
Fish of Thieves 1.0.6
Cloth Config 6.3.81

[crash-2022-09-10_01.52.12-client.txt](https://github.com/SteveKunG/FishOfThieves/files/9539885/crash-2022-09-10_01.52.12-client.txt)

**Comment by SteveKunG** [comment]
You are using an outdated version. Latest version is 1.1.0-rc1 but still in alpha.
If it still doesn't work, Try remove OptiFine.

**Comment by viiizee** [comment]
I think I figured it out. It wasn't your mod. Sorry.

**Comment by Fr0zka** [comment]
> I think I figured it out. It wasn't your mod. Sorry.

what was it ? could you tell me aha
