### ISSUE TITLE
Boot crash 1.19.2 (Fabric API 61)

### ISSUE THREAD

**Issue by SylisMC** [SteveKunG/FishOfThieves#26]
fabric-api-0.61.0+1.19.2.jar
cloth-config-8.2.88-fabric.jar
fish_of_thieves-mc1.19-v2.0.3-fabric.jar

Perhaps a repeat of [issue 25](https://github.com/SteveKunG/FishOfThieves/issues/25)

[crash-2022-09-16_16.31.28-client.txt](https://github.com/SteveKunG/FishOfThieves/files/9587138/crash-2022-09-16_16.31.28-client.txt)

**Comment by SteveKunG** [comment]
Already fixed in https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves/files/3952915
