### ISSUE TITLE
Fabric 0.14.9 - Minecraft 1.18.2 - Version 1.0.5 does not allow data pack verification

### ISSUE THREAD

**Issue by Chribit** [SteveKunG/FishOfThieves#27]
Hey,

Encountered this issue today.
Trying to update my server from fabric 0.14.5 to 0.14.9. Testing the mods in single player and creating new worlds.

The version of the mod I was using on fabric 0.14.5 is the same as now - 1.0.5.

But for some reason, I now can not load any data packs during world creation. If the mod is running, it will not allow "data pack verification" / submission of the data packs. Even if NO DATA PACKS ARE SELECTED, I can not return back to the world creation overview and get the error along the lines of "data packs could not be verified".

I've checked every other mod I have installed (i.e. removed and checked functionality) - this only occurs when fish of thieves is installed.

**Comment by SteveKunG** [comment]
You are using very outdated version. Please try 1.1.0-rc2.
https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves/files/3998940

**Comment by Chribit** [comment]
Oh shit, you‘re right. Not sure how i missed that. I‘ll try that version and get back to you!

**Comment by Chribit** [comment]
Ok, worked! Cheers!
