### ISSUE TITLE
[Quilt] 1.19.2 serverside deserialisation client crash.

### ISSUE THREAD

**Issue by netcore10** [SteveKunG/FishOfThieves#30]
Fish of thieves seems to be making me crash on my server (1.19.2) with this error.

it's a pretty destructive bug for anyone on 1.19.2

![image](https://user-images.githubusercontent.com/181536/221664942-d87b3979-452b-4ff5-bb2c-2ab67278650d.png)
https://paste.atlauncher.com/view/77643770-fad9-413e-84a6-6db1c1452cb0

Loader: quilt/fabric
Mc: 1.19.2
Mod ver: latest 1.19.2

**Comment by SteveKunG** [comment]
Are you really sure about that? I don't see any log that related to FoT.

**Comment by netcore10** [comment]
Yeah, the moment i removed fish of thieves it stopped crashing on server side.

**Comment by SteveKunG** [comment]
Can you zip entire logs folder? So I can check them all.

**Comment by netcore10** [comment]
here's the logs of the client i used that crashed before. We moved forward a bit so i can't remember the date, but if i recall, it didn't mention much 

[logs.zip](https://github.com/SteveKunG/FishOfThieves/files/10850867/logs.zip)

**Comment by SteveKunG** [comment]
Oh, I see you are using Quilt to play with FoT. I don't think my mod is playable on Quilt.

**Comment by netcore10** [comment]
that's a shame, considering it's made to be compatable with fabric mods. You basically have the only fish mod. Oh well, guess i'm at an impass.

**Comment by SteveKunG** [comment]
Yeah I know it's just a fish mod. But if you know how to do minecraft modding just port it yourself.
I'll leave this open until I have time to learn how to modding on Quilt.

**Comment by netcore10** [comment]
i did some investigating, i figured out it was a server issue causing this one problem. I don't think it was fish of theives, due to it happening elsewhere. it's just hard to test server side only issues, this crash stopped after removing FoT, but started again elsewhere.
