### ISSUE TITLE
[Quilt] Could not execute entrypoint stage 'main' due to errors, provided by 'fishofthieves'

### ISSUE THREAD

**Issue by k2helix** [SteveKunG/FishOfThieves#34]
Hello, I wanted to try out using Quilt instead of Fabric but the game crashes before launching. Here is the crash log: https://mclo.gs/5stO1yp

It does not crash without Fish of Thieves.

**Comment by SteveKunG** [comment]
Fixed in 2.4.1.

**Comment by k2helix** [comment]
> Fixed in 2.4.1.

Just updated to 2.4.1 and the same error happens caused by something different from what I see in the logs. Maybe it is because I added some other mods?

Any case, here are the logs in case you want to have a look https://mclo.gs/5GalwZ1

**Comment by SteveKunG** [comment]
I don't have time to learn how to modding on Quilt for now, If anyone wish to fix this it would be really appreciated.

**Comment by kagenyx** [comment]
i'm having the same error :( shouldn't all fabric mods be compatible with Quilt?

**Comment by Hippopipo** [comment]
Same thing here with the newest versions. You could try to ask help in the quilt forums or the quilt discord. They should be able to help there.

**Comment by SteveKunG** [comment]
As 2.2.5 the mod should be playable on Quilt and I already tested and work fine, I've updated internal code to use proper API provided by Fabric. I'll release new version soon.

**Comment by Hippopipo** [comment]
Hey, still getting this error after latest update. I use the newest version 3.0.3. Have you update the mod to fix this in this version? Anyway here are the logs [https://mclo.gs/1xDYMue](url)
