### ISSUE TITLE
Is it normal it adds overhead in the Nether?

### ISSUE THREAD

**Issue by enmumne** [SteveKunG/FishOfThieves#36]
![8o;p9;](https://user-images.githubusercontent.com/125741905/230037116-90332015-1c4f-446d-8958-387a42bb78c5.png)

I'm over the Nether ceiling testing some stuff... This shows up second in the profiler.

Why should it addFishSpawn here?

**Comment by SteveKunG** [comment]
All dimensions are already stay loaded, if there are structures around spawn chunk which allows fishes to spawn. `addFishSpawn` method would be executed. I've move `addFishSpawn` method to `SpawnHelper` class instead of `ChunkGenerator`. Hopefully it solves minor performance issue.
