### ISSUE TITLE
fishOfThieves incompatible with enviromentZ

### ISSUE THREAD

**Issue by Thefatsparrow** [SteveKunG/FishOfThieves#38]
as it says in the name. polar bears with enviromentZ mod normally drop polar bear fur

with fishOfThieves installed polar bears only drop fish from this mod and never drop polar bear fur

**Comment by SteveKunG** [comment]
I've tested. Polar Bear Furs are dropped. That's probably a bad luck for you then.
![image](https://user-images.githubusercontent.com/6128413/236409941-345065cc-956c-4fa4-8979-c662eb3c3490.png)
