### ISSUE TITLE
Bug - Immediate Crash - java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Yourname942** [SteveKunG/FishOfThieves#39]
Caused by: java.lang.IllegalArgumentException: Failed to create model for minecraft:pufferfish

MC 1.19.2
Forge 43.2.11
Fish of Thieves v2.2.3
**Latest log:** https://paste.ee/p/GeP9z

**Crash log:** https://paste.ee/p/6Dv8Z

**Comment by SteveKunG** [comment]
Can you try binary search? I don't know which mods are conflict with FOT.
