### ISSUE TITLE
No model for layer fishofthieves:headphone#main

### ISSUE THREAD

**Issue by NancalaStarry** [SteveKunG/FishOfThieves#41]
Here is the crash report:
[crash-2023-07-27_18.38.36-client.txt](https://github.com/SteveKunG/FishOfThieves/files/12182358/crash-2023-07-27_18.38.36-client.txt)

**Comment by SteveKunG** [comment]
Could you try binary search? I need to know which mods are conflict with FoT because you're playing with big mod pack.

**Comment by NancalaStarry** [comment]
Sorry I don't play this modpck anymore so... I should close this.
