### ISSUE TITLE
Crash at during loading world with MineColonies

### ISSUE THREAD

**Issue by agentwolf88** [SteveKunG/FishOfThieves#5]
[crash-2022-03-23_10.59.46-server.txt](https://github.com/SteveKunG/FishOfThieves/files/8331918/crash-2022-03-23_10.59.46-server.txt)

**Comment by SteveKunG** [comment]
Are you really sure that caused by this mod?
I see `at com.minecolonies.coremod.colony.crafting.LootTableAnalyzer.toDrops(LootTableAnalyzer.java:58) ~[minecolonies-1.18.2-1.0.526-ALPHA.jar%23135!/:1.18.2-1.0.526-ALPHA] {re:classloading}` in a crash report.

**Comment by agentwolf88** [comment]
Its maybe incompatible with Minecolonies? I have reported to the devs too.

**Comment by agentwolf88** [comment]
Minecolonies dev said: Fish of Thieves seems to be doing somethinkg funky with their loot tables. raise an issue on their github.

**Comment by SteveKunG** [comment]
After testing I found the problem on my own `LootTableLoadEvent`, especially this line.
https://github.com/SteveKunG/FishOfThieves/blob/1.18.x_architectury/forge/src/main/java/com/stevekung/fishofthieves/forge/proxy/CommonProxyForge.java#L89

Not really sure why, I will find a way to fix this later.

**Comment by SteveKunG** [comment]
Fixed in 1.0.4!
