### ISSUE TITLE
[Prominence 2 RPG] Exception ticking world Server Crash

### ISSUE THREAD

**Issue by MeowingInsanely** [SteveKunG/FishOfThieves#51]
Hello! 
Our server is currently encountering crashes & it seems to be about a Beehive & the `IslehopperVariant` from this mod?

It has been fixed by:
- Removing the most recent region (.mca) loaded by the player mentioned in the error
- Put back the region without saved entities associated with it

We sadly cannot pinpoint which was causing the crash, & how to replicate it.
Though we would apprieciate it if you could kindly show us which & what is happening in the crash log? ^^

[crash-2024-07-30_06.39.40-server.txt](https://github.com/user-attachments/files/16423094/crash-2024-07-30_06.39.40-server.txt)

Mod version: **fish_of_thieves-mc1.20.1-v3.0.2**
Modpack: [Prominence 2 RPG](https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg)
Server API: 
- Fabric API 0.92
- Fabric Loader: 0.15.11

Possible clash related to Beehives: [The Bumblezone (Quilt/Fabric)](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric)

**Comment by SteveKunG** [comment]
From a crash log it seems BeehiveBlockEntity in some mod doesn't have `honey_level` state? Could you list the blocks from the mod that has Beehive functionally? I will take a look when I'm home.

**Comment by MeowingInsanely** [comment]
There were only regular `minecraft:bee_nest` around the area, 
Additionally it was in a biome of `Autumnal Maple Forest` from [Regions Unexplored](https://www.curseforge.com/minecraft/mc-mods/regions-unexplored).

**Comment by MeowingInsanely** [comment]
Added here are the files of the regions that we suspect that has the issue:
*Remove the text before each of the `r.1.4.mca`

`(world-entities)r.1.4.mca` is for Folder: `.../world/region`
`(world-poi)r.1.4.mca` is for Folder: `.../world/poi`
`(world-region) r.1.4.mca` is for Folder: `.../world/entities`

[r.1.4.mca.zip](https://github.com/user-attachments/files/16431829/r.1.4.mca.zip)
