### ISSUE TITLE
crash with new 1.21.1 neoforge version

### ISSUE THREAD

**Issue by VaporeonScripts** [SteveKunG/FishOfThieves#53]
https://mclo.gs/DSV1lsF

**Comment by SteveKunG** [comment]
Thanks for a quick issue report! Please redownload on the Modrinth, I've removed Forgified Fabric API from the mod to fix this. You will need to download Forgified Fabric API seperately.

**Comment by VaporeonScripts** [comment]
alright

**Comment by VaporeonScripts** [comment]
im unable to make a world, it crashed,and it corrupted my current world (like if you add a custom biome mod to ur vanilla so it says it cant load) , https://mclo.gs/Ok9IcW9

**Comment by VaporeonScripts** [comment]
the mod still doesnt work,what can i do?

**Comment by SteveKunG** [comment]
Are you try to disable FoT? Crash log that you provide doesn't seems to related to my mod.

**Comment by VaporeonScripts** [comment]
Ima see today
