### ISSUE TITLE
Putting Fish in Fish Plaque also spawns the fish at 0, 0, 0

### ISSUE THREAD

**Issue by emihead** [SteveKunG/FishOfThieves#54]
Hey, I'm not sure if this is some kind of mod compat issue, but putting any Fish in a Fish Plaque also spawns a copy of that fish at 0, 0, 0. I found this from testing in a superflat world, and it happens with any fish from any mod. I'm on Forge 1.20.1, version 3.0.8.

**Comment by SteveKunG** [comment]
Hey, thanks for reporting! I didn't notice this bug until now. I will release new version later today.
