### ISSUE TITLE
NeoForge version requiring fabric_loot_api_v3

### ISSUE THREAD

**Issue by bradleywoodrs** [SteveKunG/FishOfThieves#55]
So when launching neoforge version 4.0.1 or 4.0.2, it wont let me load in with the mod, as it says it requires fabric_loot_api_v3 0.100.6 or above.

**Comment by SteveKunG** [comment]
You need to install Forgified Fabric API, because my mod is using the same loot system from Fabric. I had no choice unless Neo added a better loot system.
https://modrinth.com/mod/forgified-fabric-api
