### ISSUE TITLE
ticking entity crash 

### ISSUE THREAD

**Issue by TheRanker** [SteveKunG/FishOfThieves#6]
so here we have Fabric 1.18.2   with 0.13.3.  and fabric-api-0.48.0+1.18.2.jar
fish_of_thieves-mc1.18.2-v1.0.3-fabric

not sure whats going on.. but i was testing out my modpack and doing some work on it.. when i had a world crash.. while not in overworld. 

my modpack consists of over 300 mods.  on 1.18.2.  i have a mod called dimensional doors... which adds a roulette type dimensional door for different events.    a fish from Fish of thieves tried spawned in that dimensions water.   then this crash.

(https://pastebin.ubuntu.com/p/PDmz4yVMXv/)

https://www.curseforge.com/minecraft/modpacks/rankersmp-exploratory-revelations
is my modpack. crash happened

**Comment by SteveKunG** [comment]
Can you do more test? Try uninstall FOT, press F3 in the dimension that causes crash and send a screenshot. I wanted to see what "Biome builder PV: ..." looks like.

**Comment by TheRanker** [comment]
![image](https://user-images.githubusercontent.com/5889820/160673657-42074002-d03d-4624-bb07-2276cc4aab6c.png)
your mod still enabled . as its only upon the fish spawning i believe.

**Comment by TheRanker** [comment]
the doors take you to a random premade dim. theres a whole bunch of them.. so to get the specfic one i crashed in before,, may prove to be difficult. this one has water so i would expect simliar results if fish spawned

edit... forced spawn of fish...
[crash-2022-03-29_15.23.51-server.txt](https://github.com/SteveKunG/FishOfThieves/files/8373858/crash-2022-03-29_15.23.51-server.txt)

**Comment by SteveKunG** [comment]
Fixed in 1.0.6, it shouldn't crash in other dimensions anymore. Hopefully.
