### ISSUE TITLE
There are no tool tip for Fish-Buckets in 1.18.1 Forge

### ISSUE THREAD

**Issue by FireMuffin303** [SteveKunG/FishOfThieves#8]
At first, I reload resource pack then the game crash.

so I checked crash report file and found the problem with the fish-buckets.

later, I hover my cursor to the fish-buckets then crash.

Here's the crash-report
[crash-2022-03-30_21.16.08-client.txt](https://github.com/SteveKunG/FishOfThieves/files/8381281/crash-2022-03-30_21.16.08-client.txt)

**Comment by SteveKunG** [comment]
Can use test on 1.18.2? 1.18.1 is out of support.

**Comment by FireMuffin303** [comment]
It's fine on forge 1.18.2.

I want to make a modpack to play with friends on 1.18.1 since most of the mods we love are on 1.18.1 and not update to 1.18.2 as well.

**Comment by SteveKunG** [comment]
All mods should be on 1.18.2 for nowadays, hopefully a problem that you got should no longer occurred.
